DELETE http://localhost:8080/events/1/register
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NTc0OTAyODEsInVzZXJJZCI6MX0.9DfHs70QM37TvL1QP80Ovw2uDotLePdIhbW3mIXvbzI