DELETE http://localhost:8080/events/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzU3NDg1NDA5LCJ1c2VySWQiOjJ9.6kwtM-KaAgRufpBCNm6Pc4Oy6S1mKCF1WB52Rl8lIaY